### ISSUE TITLE
ulong64 returned hash is not always the same bytes long

### ISSUE THREAD

**Issue by marcolino** [mgmtio/phash-image#10]
pHashImage = require('phash-image');

    pHashImage(imagePath, true).then(function(hash) {
        console.log('hash length:', hash.length);
        hash = _.padRight(hash, 20, '0'); // <== I wouldn't expect to have to do this !
      });

Sometimes returned hash length is 20, sometimes it is 19!!!

**Comment by jonathanong** [comment]
any idea why this happens and how to fix it? do you have a sample image?

**Comment by marcolino** [comment]
It looks to me (I didn't debug the issue) it could be a problem about the cast from number to string (0.49 => "0.49", 0.50 => "0.5"), but I don't know why decimal numbers should be used, in this algorithm...  It could be also something related to digit "0" being considered a boolean, and being wrongly converted to empty string, instead of to "0"... I did hope the simple description of the issue could switch on some light in you... :-) I'll try to give you an image which causes the issue (I think it's not difficult, I think I found the issue for many of the images I did try...), or, better, will debug the issue ASAP, and will issue a PR...

**Comment by jonathanong** [comment]
hmmm... that cast from number to string in C++ land... i'm not too good with C++!

**Comment by marcolino** [comment]
Why C++? Just speaking about JS...

**Comment by jonathanong** [comment]
sorry. that cast occurs in C++ to a string and is converted in JS to a buffer via `hex.slice(2)` since the two first characters are `x0` or whatever.

**Comment by marcolino** [comment]
So, will the issue (variable hash length) be fixed?

**Comment by jonathanong** [comment]
i need a reproducible test case =/ otherwise i don't know where to investigate

**Comment by marcolino** [comment]
You're right...
Currently I am testing Jimp (https://github.com/oliver-moran/jimp), so I don't have an example anymore, sorry... But I suppose it shouldn't be difficult to find one: I remember one out of 4 or 5 images hash was 19 bytes long... :-(
