### ISSUE TITLE
CImg problems with MacOS

### ISSUE THREAD

**Issue by dreampulse** [mgmtio/phash-image#11]
Hi,
I get the following error:
```
/usr/local/Cellar/phash/0.9.6_1/include/pHash.h:50:10: fatal error: 'CImg.h'
      file not found
#include "CImg.h"
         ^
```

a solution to this error is to add the cimg include path by hand
```
      "include_dirs" : [
        "<!(node -e \"require('nan')\")",
        "/usr/local/Cellar/cimg/1.6.3/include"
      ]
```

unfortunately I do not know how to fix this in a generic way

**Comment by jonathanong** [comment]
how did you install CImg?

**Comment by dreampulse** [comment]
with ```brew install cimg````
I get cimg-1.6.3

**Comment by DeX3** [comment]
+1ing this, I get the same issue. Can I somehow add the cimg installation to node-gyp's include path globally?

**Comment by jonathanong** [comment]
anyone know of a generic way?

**Comment by lovell** [comment]
https://github.com/lovell/sharp/blob/master/binding.gyp#L58 provides an example of building a cross-platform (OS X, Linux) `pkg_config_path`, which can be used via something like https://github.com/lovell/sharp/blob/master/binding.gyp#L67

**Comment by jonathanong** [comment]
@lovell i'm not sure that's it because i don't see `cimg`'s package config file anywhere

**Comment by jonathanong** [comment]
maybe i just don't understand how pkg-config works

**Comment by jonathanong** [comment]
```
      "include_dirs" : [
        "<!(node -e \"require('nan')\")",
        "/usr/local/include"
      ]
```

is that okay? that seems to work since `cimg.h` is in `/usr/local/include`
