### ISSUE TITLE
Error when trying to install from npm

### ISSUE THREAD

**Issue by bugs181** [mgmtio/phash-image#19]
Getting an unusual error when trying to install from npm. Let me know if I can provide any further information.

**OS:**
`$ sw_vers`
    ProductName:	Mac OS X
    ProductVersion:	10.10.1
    BuildVersion:	14B25

**phash:**
`$ brew install phash`
`Warning: phash-0.9.6_1 already installed`

**Node version**:
`$ node -v`
`v5.7.1`

**npm version:**
`$ npm -v`
`3.6.0`

Alternatively tried with these versions (same result)

**Node version**:
`$ node -v`
`v4.4.1`

**npm version:**
`$ npm -v`
`2.14.20`

**Error:**
`npm-debug.log`

    379 verbose stack Error: phash-image@3.5.0 install: `node-gyp rebuild`
    379 verbose stack Exit status 1
    379 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
    379 verbose stack     at emitTwo (events.js:100:13)
    379 verbose stack     at EventEmitter.emit (events.js:185:7)
    379 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    379 verbose stack     at emitTwo (events.js:100:13)
    379 verbose stack     at ChildProcess.emit (events.js:185:7)
    379 verbose stack     at maybeClose (internal/child_process.js:827:16)
    379 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    380 verbose pkgid phash-image@3.5.0
    381 verbose cwd /Users/....
    382 error Darwin 14.0.0
    383 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phash-image"
    384 error node v5.7.1
    385 error npm  v3.6.0
    386 error code ELIFECYCLE
    387 error phash-image@3.5.0 install: `node-gyp rebuild`
    387 error Exit status 1
    388 error Failed at the phash-image@3.5.0 install script 'node-gyp rebuild'.
    388 error Make sure you have the latest version of node.js and npm installed.
    388 error If you do, this is most likely a problem with the phash-image package,
    388 error not with npm itself.
    388 error Tell the author that this fails on your system:
    388 error     node-gyp rebuild
    388 error You can get information on how to open an issue for this project with:
    388 error     npm bugs phash-image
    388 error Or if that isn't available, you can get their info via:
    388 error     npm owner ls phash-image
    388 error There is likely additional logging output above.
    389 verbose exit [ 1, true ]

**Comment by jonathanong** [comment]
i think you're missing the actual error logs above this log

**Comment by PlasmaPower** [comment]
This is most likely due to Node being unable to find Phash, but we'll need the error messages above the ones you posted to debug this. IIRC you might need to do `brew link phash` to symlink the libraries, but that's just from memory (never had a mac, never used homebrew).

For now, I'm going to close this issue as we lack the information to troubleshoot it further.
