### ISSUE TITLE
Calculate video phash

### ISSUE THREAD

**Issue by Sparragus** [mgmtio/phash-image#9]
I've been using this module for a while and now I'm interested in using it for video files like gif and mp4. From reading the source code I noticed that there is no support for video files.

The original phash.h library has [support for video files](https://github.com/sdepold/pHash/blob/master/src/pHash.h#L342-L350). Is there a plan to add support for video? How about we do this together. At least I'm interested in having support for it.

Or someone knows about a different (node) module that already does this. Can you point me to it?

So, anyone else interested? Maybe we should start a conversation here about it.

**Comment by Sparragus** [comment]
So I found this by you guys: [mgmtio/video-phash-service](https://github.com/mgmtio/video-phash-service/blob/master/lib/phash-file.js).

Checking out it seems you guys produce all the frames using ffmpeg and calculate the phash for each of them. How good of an approach has this been for you?

**Comment by jonathanong** [comment]
@Sparragus that is for scene detection, not for comparing videos. different things

**Comment by jonathanong** [comment]
PR welcomed!
